### ISSUE TITLE
Develop botkit module for dialog messenger

### ISSUE THREAD

**Issue by Maay** [dialogs/dialog-botkit-module#1]
We are the team of corporate messenger dialog. We have Java/ Python/JavaScript Bot SDK to create bots in our messenger. Since it is new, we want to order a few bots from the community for demonstration purposes.

The documentation of our Java Bot SDK is here: https://docs.dlg.im/bots/java-bot.html

The documentation of our Python Bot SDK is here: https://dialogs.github.io/python-bot-sdk/ ⁣ ⁣ ⁣

The documentation of our JavaScript Bot SDK is here: https://dialogs.github.io/js-bot-sdk/

**Our messenger has a web client, you should use it for the development**: https://grpc-test.transmit.im/
* For web use endpoint: https://grpc-test.transmit.im:8443
* For grpc use endpoint: https://grpc-test.transmit.im:9443
* Test accounts:
alice / password

After you've logged in you should write to `Security Bot` user and write command `/bot new bot_username bot_name` where `bot_username` is the username you can choose for your new bot and `bot_name` his display name

We've open-sourced several bots that you can look up to https://github.com/dialogs?utf8=%E2%9C%93&q=-bot&type=&language=

Please feel free to ask questions in our community https://dlg.im/@botsfordialog ⁣ ⁣

Our developers are always happy to help and answer your questions.

[Botkit](https://botkit.ai) is popular tool "for building chat bots, apps and custom integrations for major messaging platforms".

**We need an module that connects Botkit with dialog.**

We recommend using this documentation for developing module
https://botkit.ai/docs/howto/build_connector.html

Using this module bots should be able to:
Send text
Receive text
Receive chat userlist 
Detect new user in chat
Send file
Send image
Use [interactive elements](https://docs.dlg.im/bots/java-bot.html#interactive-elements)
[Update interactive elements](https://docs.dlg.im/bots/java-bot.html#update-interactive-elements)

Take a look at some of the modules to get some ideas for your implementation:  [Slack](https://botkit.ai/docs/readme-slack.html) ⁣ ⁣and [Facebook Messenger](https://botkit.ai/docs/readme-facebook.html).

For [bounty](https://www.bountysource.com/issues/70910061-develop-botkit-module-for-dialog-messenger) to be verified it’s necessary to create documentation with instructions as it is done for Slack and Facebook modules.

**Comment by Maay** [comment]
@terorie FYI ;)

**Comment by willy2dg** [comment]
Is this issue asigned then ?

**Comment by Maay** [comment]
@willy2dg no, we've got no confirmation from @terorie, so you can start

**Comment by willy2dg** [comment]
@Maay Just to be sure. You want a BotKit connector which parses the web chat  ( taking the html or js )  to get the mentioned logic ( working on the current chat, no channels involved ) ?

**Comment by terorie** [comment]
@Maay @willy2dg I will start working on the BotKit connector. I'll give you an ETA as soon as I have one 👍

**Comment by Maay** [comment]
@terorie great, thank you!

**Comment by Maay** [comment]
@terorie any luck?

**Comment by terorie** [comment]
@Maay I'm on it, will push later today

**Comment by terorie** [comment]
I hope to finish by Wednesday

**Comment by terorie** [comment]
Sorry for the delay. The bot is about 80% done, I just need interactive user responses and interactive updates.

As far as I know, `Receive chat userlist` is not mentioned anywhere in the Botkit docs, so I have to come up with good API design on that.

**Comment by Maay** [comment]
@terorie great news!

**Comment by Maay** [comment]
Any luck with `Receive chat userlist`?

**Comment by terorie** [comment]
@Maay I'm stuck, unfortunately. Most of the functionality is done however.
Feel free to merge the current part. I will claim the bounty later in a second PR when everything else is done.

**Comment by Maay** [comment]
@terorie please check this issue as solved on bountysource

**Comment by terorie** [comment]
@Maay Thanks, I marked it
